### ISSUE TITLE
Multiple URLs Feature Request

### ISSUE THREAD

**Issue by techteacher47** [Xonshiz/comic-dl#11]
Is there any way to input a range of URLs, where only one part of the URL changes? For example, the link http://www.omgbeaupeep.com/comics/Richie_Rich/647/ differs from similar links by changing the 3-digit number. So the feature would allow for something like comic_dl.exe -i http://www.omgbeaupeep.com/comics/Richie_Rich/001-647/. This would only apply to sites that do not have an index page for a series of books. Thank you!

**Comment by Xonshiz** [comment]
Yep, that's totally doable and I was thinking the same when I released the update. I have to re-write this whole module because this website doesn't seem to have a naming convention.

For example, read [this line 50](https://github.com/Xonshiz/comic-dl/blob/master/comic_dl/sites/omgbeaupeep.py#L50). I thought I notices a pattern in their file naming, but I was so wrong. They have weird naming convention. Because of this, I'll have to re-write everything for this.

I will try to do it by the end of this week. If I can't, then next month (I have exams from 16th).

**Comment by techteacher47** [comment]
That is strange. Thanks so much for looking into it when you can. Good luck on your finals!

**Comment by vomov** [comment]
@techteacher47 
I use a batch file that calls the exe with different urls. It's not pretty, but it does work very well.

**Comment by marlon99rocks** [comment]
you can open 3 cmd then enter 3 same comands on 3 cmd in windows 10

**Comment by marlon99rocks** [comment]
![image](https://user-images.githubusercontent.com/23298994/27422571-03cdbcce-5772-11e7-99b6-1ccbcd28a619.png)

**Comment by vomov** [comment]
@marlon99rocks 
Your way puts you at risk for bans, as you're putting quite a bit of pressure on a single server (assuming you're getting three comics fro one server, here).

It's easier and safer to just make a batch file and copy-paste the links you want. If you don't want to make a batch file, just give multiple commands on a single line in cmd; the effect is the same.

**Comment by marlon99rocks** [comment]
how do i make batch file

**Comment by vomov** [comment]
@marlon99rocks 
[http://lmgtfy.com/?q=how+to+make+a+batch+file](url)

Short answer; make a text file, put the commands you want in it, and change the extension to '.bat'

**Comment by marlon99rocks** [comment]
i dont under stand it i got rid of my other downloads so like this
comic_dl.exe --sorting asc -i (url) --sorting i- (url)

**Comment by vomov** [comment]
@marlon99rocks 
It doesn't matter if you're giving a command in a cmd window or a batch file; you're using the exact same command. 

For example, if I want to download the Watchmen prequels, because I don't want to drag my hard copies around, I can open a command window, and feed the following:
`comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Rorschach'
But then I'd have to manually start the next comic.

I can chain multiple commands using batch, but easier is to simply open a txt file, and add the following:
`comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Rorschach
comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Ozymandias
comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Nite-Owl
comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Moloch
comic_dl.exe -i http://readcomiconline.to/Comic/Before-Watchmen-Dr-Manhattan`
I then rename the .txt to .bat, start it, and walk away.

**Comment by Xonshiz** [comment]
Using batch files and downloading all these urls is a nice hack, but also a nice way to get your IP banned. So, it's recommended that after downloading 1 series from a website, cool down for a few minutes and then try with the new one. It'll be better. Otherwise, the script will fail if you get your IP banned.

**Comment by vomov** [comment]
@Xonshiz 
Corporate networks also don't always like this kind of behavior (although our firewall is set to insane levels anyway). I usually use TIMEOUT to let it sleep for ten minutes before downloading the next one.

**Comment by Xonshiz** [comment]
ah, that's great :D
But, when you post a hack like this, please do mention what steps you take to get away. So that the other people going for the hack also know what consequences they can face.

**Comment by Xonshiz** [comment]
Support for range added! Please test it out on your end.
