### ISSUE TITLE
https://github.com/Xonshiz/comic-dl/blob/master is unavailable

### ISSUE THREAD

**Issue by azumukupoe** [Xonshiz/comic-dl#139]

**Comment by Xonshiz** [comment]
It is unavailable because you're using it wrong (as far as I know). If you need a permanent link to a particular file from comic-dl repo, then you need to append that file's name at the end. For example : to get the `ReadMe.md` file, you would make this url : https://github.com/Xonshiz/comic-dl/blob/master/ReadMe.md

Closing this because it's an invalid question/issue and not related to comic-dl. Please re-open with proper description of the problem.

**Comment by Xonshiz** [comment]
And if I missed something or interpreted it wrong, please correct me so I can look into it.

**Comment by Xonshiz** [comment]
Oh, okay, got it. Nice catch. And next time you open any issue on any repo, please do provide some details :)

**Comment by azumukupoe** [comment]
Sorry for that

**Comment by Xonshiz** [comment]
No issues. I've updated the link. Please check back again :)
