### ISSUE TITLE
Output format is WebP?

### ISSUE THREAD

**Issue by shinji257** [Xonshiz/comic-dl#170]
I did a test download using this program and I found that all the images use JPG for an extension but are actually WebP.  Can you convert them to actually be JPG or link me a reliable program to quickly convert the images?

Example that ended up with WebP output images: https://mangarock.com/manga/mrs-serie-60319/chapter/mrs-chapter-60320

I'm using the pre-release build from #163

**Comment by darodi** [comment]
@shinji257 
you could use irfanview, it's a freeware
https://www.irfanview.com/

open a file, then go in the menu:
file > batch conversion / rename

select all the files for input, click add all
select the output format: jpg
select the output directory
then click "start batch"

**Comment by cooperspencer** [comment]
@darodi 
you could also convert the webp files with pillow

```
from PIL import Image

src = 001.webp
out = 001.jpg

im = Image.open(src)
rgb_im = im.convert("RGB")
rgb_im.save(out)
os.remove(src)
```

**Comment by darodi** [comment]
@cooperspencer 
good idea, I added this in the last pull request.

@shinji257 
in next version, you'll be able to add `--convert jpg` 
example:
`comic_dl.exe -i https://mangarock.com/manga/mrs-serie-60319/chapter/mrs-chapter-60320 --convert jpg`

**Comment by darodi** [comment]
@Xonshiz 
I've seen you have closed PR #179 too.

As I said, mangarock is currently decrypting files that are .webp files.
It is saving them with extension .jpg.
That is incorrect and should be fixed to use the correct extension for the webp format.

But you shouldn't force users to use .jpg instead of .webp !
Many readers are able to read .webp files. 
webp uses a better compression algorithm, a lossless codec (like png) and takes less space.
Decrypting + converting to jpg by default doubles the download time for a chapter and is a compression with loss.
I really see no point in converting by default to jpg...

**Comment by darodi** [comment]
same remark for .png extensions.
some modules save .png files as .jpg.
That is incorrect and should be fixed.

**Comment by Xonshiz** [comment]
Closing this, as it has been discussed and address properly now.
