### ISSUE TITLE
Show the list of a comic's chapters/issues

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#176]
it could be an argument

**Comment by Xonshiz** [comment]
That is present already, I guess. The part of comic-dl that lets you search within CLI and download the manga, that functionality already has this IIRC. But, for comics, it'll be useless. Because you need to provide a link to the main series and when you open your browser to get that link, you already see the list of chapters/issues.

I might be interpreting this completely wrong, please clarify if that's the case.

**Comment by darodi** [comment]
seems a duplicate of #164

**Comment by DyeffersonAz** [comment]
NOW duplicate from #164
