### ISSUE TITLE
Qiremanhua

### ISSUE THREAD

**Issue by ghost** [Xonshiz/comic-dl#193]
you can add www.qiremanhua.com, it has better quality than ac.qq.com

**Comment by Xonshiz** [comment]
Will look into this.

**Comment by Xonshiz** [comment]
Added support for this. There seems to be a "content lock" for the latest releases. Haven't added a login system because I didn't want to share my phone number and other details with a website I'm not going to use.
So, as a workaround, you could log in via browser manually and grab the cookie after logging in and then pass that cookie via `--cookie` argument and it should hopefully download the locked content too.
