### ISSUE TITLE
Readcomiconline.to no longer working

### ISSUE THREAD

**Issue by sephiroth1993** [Xonshiz/comic-dl#245]
Like the title says, https://readcomiconline.to/ no longer works:

```
comic_dl.exe -i https://readcomiconline.to/Comic/Coda/Issue-1?id=133851
Fooling CloudFlare...Please Wait...
[Comic-dl] Done : Coda [Issue - 1] : : 0image(s) [00:00, ?image(s)/s]
Total Time Taken To Complete : 12.0090000629
```

![imagen](https://user-images.githubusercontent.com/6667667/62475014-84000e00-b77a-11e9-8458-d6f2bc9d8425.png)

0 images 😐

**Comment by dsanchezseco** [comment]
I had no problem, but i'm using the python version instead of the exe, try with that one

**Comment by britojr** [comment]
I'm using the python script and also can't download anything from readcomiconline.to.
It gives this error:

```
Fooling CloudFlare...Please Wait...
Traceback (most recent call last):
ValueError: could not convert string to float: b'undefined'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
ValueError: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

I already updated cfscrape to version: 2.0.8

I see that it is asking for a bug report, but since there are some people who are still able to download with this version of the code, maybe it could be because of something else.

**Comment by MatevzKu** [comment]
From my experience so far - when you see 0 of 0 images it means that the website put you on a blacklist for a while. Wait for (quite) a bit and try again, with a only a single chapter. 

I had the same issue and discovered that it happens after downloading a whole series - after 5 or 6 chapters i got blocked.

**Comment by Aemilian666** [comment]
Please also note that the blacklist seems to be permanent, and your only option is to use a VPN.

**Comment by AtomR** [comment]
`ValueError: Unable to parse Cloudflare anti-bot IUAM page: jschl_vc is missing from challenge form Cloudflare may have changed their technique, or there may be a bug in the script.`

Also got this. 

I used to use another executable to download comics from readcomicsonline and it stopped working yesterday. The problem was also cloudflare so they might have changed something on the way it protects websites from this type of usage.

**Comment by Xonshiz** [comment]
Should work now.
