### ISSUE TITLE
i just found out something

### ISSUE THREAD

**Issue by marlon99rocks** [Xonshiz/comic-dl#26]
i cant download from http://readcomiconline.to/ but i can download from http://www.mangahere.co

**Comment by Xonshiz** [comment]
Dude, seriously, before using this script, go through the [Read Me](https://github.com/Xonshiz/comic-dl/blob/master/ReadMe.md) and post your query accordingly.

Writing that read me has taken 30 minutes or so, please go through it. I'm closing this issue because you're not following the guidelines. Please re-post with verbose and I'll look into it.
