### ISSUE TITLE
The script says the name of the comic but it doesn't download it

### ISSUE THREAD

**Issue by Alexandre95sang** [Xonshiz/comic-dl#31]
Good morning/afternoon/evening,
The script used to work very well. But after **exactly** 100 comics downloaded, it just stopped working. 

Now, when I try to download a comic, the script shows the name of the comic (as it does normally before it starts downlading it), but in my case, after it shows the name, it just acts as it finished downloading it and says "Total time taken ....".
 
![cmd_2017-06-30_13-48-07](https://user-images.githubusercontent.com/29797152/27734356-c5b2ae98-5d9a-11e7-9966-62cd763b2580.png)

At first I thought I'd had to wait, that the site blocked the connection because of too many requests, but after 12 hours it is still not working. I don't know if I should wait more, but I would think 12 hours would be more than sufficient.

Sory bade englich

**Comment by Xonshiz** [comment]
There's no estimated time that you can guess that you should wait. 100 Chapters in one go is more than enough that I had planned that the script could do. 

Try to open the same webpage via your browser and see if there's any "human verification" check or not.

Wait for a day and `Run the script with --version, which will generate a verbose log`. Post that log file/text from that log file on a gist and share that gist's link here.

Check [this issue](https://github.com/Xonshiz/comic-dl/issues/4) and see how he posted the verbose log.

Just a friendly advice, whenever you report a bug for a program, please make sure you go through its [ReadMe](https://github.com/Xonshiz/comic-dl#opening-an-issuerequesting-a-site) and post the information accordingly.

Since this is an IP block issue that happens when you download a bunch of chapters altogether, this is not comic-dl's issue. I'll be closing this issue until you post the verbose log.

**Comment by Alexandre95sang** [comment]
I had opened the webpage to see if there was a captcha, and there was none.

I have run the -v command : https://gist.github.com/Alexandre95sang/9baea150314d17c69ee240d1df0db36c
Apparently it's an error 503

So I think waiting more should be the solution.
Thank you very much for your quick response. I will post an update in 24 hours.

**Comment by Xonshiz** [comment]
Yep, waiting is the only thing you can do. Also, you're using windows binary? 

If you're using Python script, I'd suggest that you clean the .pyc files and __pycache directory.

**Comment by Alexandre95sang** [comment]
Yep, I am using windows binary.
You were right, waiting was the solution. Sorry for not being patient!

Thank you very much for your work.

**Comment by DyeffersonAz** [comment]
@Xonshiz , I have a solution if there are none "Human Verification", other thing the guy can do is to open the site in another browser. It worked to me ;)
