### ISSUE TITLE
[UBUNTU 20.04] -> Can't download, <403> error

### ISSUE THREAD

**Issue by DiegoNG90** [Xonshiz/comic-dl#314]
Hi
![image](https://user-images.githubusercontent.com/63425447/165859043-df04c0b2-5477-4a77-be4c-909a3cb6dbfd.png)
Any ideas?

**Comment by Xonshiz** [comment]
Hello, a few things:
1.) Please go through the [Notes section](https://github.com/Xonshiz/comic-dl#notes) of the readme. The very first point explains this exact same issue.
2.) Why use an `.exe` on Linux? There's a separate Linux binary (has been there for a long time). Not that it'll change things, but you won't need `wine` for running it.

Since this is a duplicate issue, closing this one.

**Comment by Xonshiz** [comment]
Just to add, if even after using the `--cookie` option it's not working, please feel free to continue the conversation in #299, I'll re-open that one.
