### ISSUE TITLE
Updated list of supported websites?

### ISSUE THREAD

**Issue by DarklySatanic** [Xonshiz/comic-dl#345]
Hey guys,
not really an issue, but since using the 'Search' feature didn't give me the answers I seek, I figured I'd ask here.

Is there a list of currently supported websites, as of this evening, 06 November, 2023? 

A few of them, like readonline.io or something to that effect doesn't seem to work on my browser. 
Comicextra.me just doesn't seem to work at all. The only relevant mention of this host in the 'Search' features mentioned that the Comic_dl binary was not updated for the user, and/or the website is down. 

Unfortunately, it doesn't seem like the website is currently supported, as stated by the cmd error, as well as the fact that I have the most recent binary as of Aug 2023.

Any help would be appreciated! Not a super-big Manga reader, so very curious about other straight-comic websites, as Comicextra was my go-to whenever RCO was screwing up.

**Comment by Xonshiz** [comment]
The list hasn't been updated and this project hasn't been maintained in a long time. Unfortunately, because of my schedule these days. If the website doesn't work anymore, but it's mentioned in the supported website list, then it's a bug and I'd request you to raise an issue for it.
Readcomiconline has been an issue for quite some time and if you can't download from RCO, sorry but that can't be fixed due to technical restraints on bypassing the Cloudflare check.

**Comment by DarklySatanic** [comment]
Aha, that makes sense, thanks for replying!

I shall look forward to potential new websites in the future, when your time is once again a bit more free. =)
