### ISSUE TITLE
Not able to download from readcomicsonline.li

### ISSUE THREAD

**Issue by JaegerMaster** [Xonshiz/comic-dl#347]
I get the below error when trying to download from readcomicsonline;li as well as readcomicsonine.ru

```
comic_dl -i https://readcomiconline.li/Comic/Spider-Man-Battlebook-Streets-of-Fire/
Fooling CloudFlare...Please Wait...
Whoops! Seems like I can't connect to website.
It's showing : <Response [403]>
Run this script with the --verbose argument and report the issue along with log file on Github.
Traceback (most recent call last):
  File "/opt/comic-dl/cli.py", line 5, in <module>
    main()
  File "/opt/comic-dl/comic_dl/__main__.py", line 20, in main
    ComicDL(sys.argv[1:])
  File "/opt/comic-dl/comic_dl/comic_dl.py", line 204, in __init__
    honcho.Honcho().checker(comic_url=user_input, current_directory=os.getcwd(),
  File "/opt/comic-dl/comic_dl/honcho.py", line 101, in checker
    readcomicOnlineli.ReadComicOnlineLi(manga_url=comic_url, logger=logging,
  File "/opt/comic-dl/comic_dl/sites/readcomicOnlineli.py", line 44, in __init__
    self.full_series(comic_url=manga_url.replace("&readType=1", ""), comic_name=self.comic_name,
  File "/opt/comic-dl/comic_dl/sites/readcomicOnlineli.py", line 135, in full_series
    source, cookies = globalFunctions.GlobalFunctions().page_downloader(manga_url=comic_url, scrapper_delay=10, append_headers=self.appended_headers)
  File "/opt/comic-dl/comic_dl/globalFunctions.py", line 60, in page_downloader
    raise Warning("can't connect to website %s" % manga_url)
Warning: can't connect to website https://readcomiconline.li/Comic/Spider-Man-Battlebook-Streets-of-Fire
```

**Comment by tabletseeker** [comment]
Try out the only working downloader for readcomicsonline.li in 2024:

**Comment by DarklySatanic** [comment]
You were authorized to promote this on another Github?

**Comment by DarklySatanic** [comment]
@lmagdanello

You able to make sense of any of this? His repo doesn't include any sort of viable readme.

**Comment by tabletseeker** [comment]
> You were authorized to promote this on another Github?
> 
> Also, there's a slight but jarring difference between your github and this one -

Yes there is, mine works lmao.

> This one actually had a clear Readme.

I don't need an extensive readme, because my project uses a GUI which contains all necessary info.

This 3 page readme is useless because your code is broken and simply doesn't work on readcomiconline.li

**Comment by DarklySatanic** [comment]
> > You were authorized to promote this on another Github?
> > Also, there's a slight but jarring difference between your github and this one -
> 
> Yes there is, mine works lmao.
> 
For you. For now. 

> > This one actually had a clear Readme.
> 
> I don't need an extensive readme, because my project uses a GUI which contains all necessary info.
> 
All you say is 'Clone the Repository'. You don't specify that people will need to get Git Bash in order to do so. You don't indicate where to get those items that you mention in your Debian. 

You may not need an extensive readme, but you sure as hell are going to alienate a *lot* of people. 

> This 3 page readme is useless because your code is broken and simply doesn't work on readcomiconline.li

It isn't my code. Also, it may be broken now, but that's because the developer isn't maintaining it. It is broken because of his lack of time, not for any sort of inability to do so.

**Comment by tabletseeker** [comment]
I see, so this isn't even your code then. That explains why you would tell a GitHub developer to add instructions for installing git, makes sense.

It's a 100% shell script, as clearly indicated. What would one expect to run a shell script with?

The reason why this project is useless for readcomiconline is because they have effectively rendered all methods of using wget, curl, phantomjs, puppeteer etc. obsolete. The only way to load from that page is by fully rendering with a correct fingerprint which at the time is simply impossible unless an actual browser instance is used.

Meaning, the way I do it is the **only way** it can be done right now.

Secondly, my code is flawless, buddy. It works perfectly and you should've simply read the instructions before opening an issue.

**Comment by darodi** [comment]
>Try out the only working downloader for readcomicsonline.li in 2024
_Originally posted by @tabletseeker in https://github.com/Xonshiz/comic-dl/issues/347#issuecomment-1885086107_
            
You are a bit pessimistic here... Every other downloader using selenium works fine and is not limited to Linux. :grin:
It's using a browser too but `comic-dl` didn't want to add that dependency.

Anyway, I didn't know `xdotool`, seems a great tool. Nice discovery.

**Comment by tabletseeker** [comment]
> > Try out the only working downloader for readcomicsonline.li in 2024
> > _Originally posted by @tabletseeker in [#347 (comment)](https://github.com/Xonshiz/comic-dl/issues/347#issuecomment-1885086107)_
> 
> You are a bit pessimistic here... Every other downloader using selenium works fine and is not limited to Linux. 😁 It's using a browser too but `comic-dl` didn't want to add that dependency.

No, no we're talking about readcomiconline.li here. Mine is literally the only downloader that works with that site, because they've deliberately taken measures to stop conventional methods such as selenium or phantomjs. It won't work.

**Comment by darodi** [comment]
I'm using a selenium python app with rco for years. It is just not shared publicly and I don't intend to.
Have a look for `undetected_chromedriver` library, selenium methods work fine.
It drives a browser as a normal user would.

**Comment by darodi** [comment]
@tabletseeker 
And please... stop spamming every issue in this repository, and other repositories with ads to your project. 
Learn to behave.

@Xonshiz 
FYI. I'm notifying you, if you haven't seen it and need to take action :smiling_imp:

**Comment by tabletseeker** [comment]
This could technically work but seems like complete overkill for something so simple.

Also, you need a virtual environment on top because of focus issues. With xdotool you can simply fix a dedicated workspace for the script + browser and simultaneously use another to do something else.

As for spam, I do what I must to spread superior and more efficient code.

**Comment by darodi** [comment]
@tabletseeker 

Try to read libraries documentation before talking nonsense. 
A python script takes less than 300 lines. Your efficient bash scripts: 2 * 220 lines.
Selenium can drive a new browser window and hide it at the same time. I don't see the point of a virtual environment,
and it works with every OS.

But anyway, this is not the purpose of `comic-dl`. Its aim is to be kept simple without many libraries, no browser needed, no web driver needed. A simple .exe file. 
That has been said by the author @Xonshiz numerous times.

What am I doing... I should stop discussing with Übermensch/Übercoders. 
I'm just wasting your superior precious time needed to spread your superiority to all those inferior beings. 
I'm so sorry to disturb you with all our inferiority. That must be so difficult for you!
I'm waiting for you next superior project. A superior spamming script?

**Comment by tabletseeker** [comment]
80% of my script is dialog/gui. The actual code is under 40 lines, you should try to read yourself before talking nonsense. Do you read Python or Shell by any chance?

Also, this project does absolutely nothing because it has been broken and abandoned for 5 years.

Even if you could use this with Selenium, which you can't because the way comic-dl processes links is flawed, the maintainer's code is missing another vital aspect that would break usage with readcomiconline.li 
What he didn't consider, is that captchas are triggered if the script loads multiple pages with the same intervall. The wait time has to be random to circumvent this.

But why am I talking to some lowly end-user who probably has no idea what I'm saying in the first place?

**Comment by Xonshiz** [comment]
Thanks for the tag, @darodi . I've been following this thread, but didn't think to join in the hopes that the nonsense would stop. But, looks like the kids don't know how to behave.
@tabletseeker , I generally allow people to share discuss and about different libraries because as long as something is built to help people download things, I'm happy  with the alternative. But, there's a difference between sharing the things to help people and being an arse.
It's good that you built a tool that works...for now. But, you're comparing oranges and apples here. As darodi mentioned, the goal was to keep this library simple to setup and use. Also, this library is pretty old and the main thing, if you're genius brain hasn't noticed. Comic_dl isn't just for RCO. It's a tool to download comics and manga from various sources. You wouldn't know, but  it's difficult to maintain a tool that I started as a fun project when I was in college and now I'm not. So, things change.
If you go through the readme, you'll notice this tool can do much more than just download comics from  RCO. Had you went through it, it probably would've saved some embarrassment. 

Anyways, thanks for making the RCO download tool,and I'll let this thread and your comments be there. But, I'm locking the thread because as I mentioned, you're crossing lines by being an arse.

**Comment by darodi** [comment]
Get a life man!

For most people, github and open source is a hobby. This project is not actively maintained because some persons here, do indeed have a life. You don't seem to comprehend that. 

If you are not happy with it, create pull requests and improve it, that would be a constructive approach
...or fork the project, or create your own as you did. 

But goddammit, just stop denigrating other projects and spamming everywhere on github for your project.
You are not welcome here for that.
