### ISSUE TITLE
Latest Windows Binary reports "EnvironmentError, Missing Node.js runtime"

### ISSUE THREAD

**Issue by Tamalero** [Xonshiz/comic-dl#35]
Debug:
DEBUG: Arguments Provided : Namespace(convert='None', download_directory=None, input=['http://readcomiconline.to/Comic/Guardians-of-the-Galaxy-2015'], keep='True', range=['1-19'], sorting=None, verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.14393
DEBUG: Python Version : 2.7.13 (32bit)
DEBUG: Comic Url : http://readcomiconline.to/Comic/Guardians-of-the-Galaxy-2015
DEBUG: Selected Domain : readcomiconline.to
DEBUG: Starting new HTTP connection (1): readcomiconline.to
DEBUG: http://readcomiconline.to:80 "GET /Comic/Guardians-of-the-Galaxy-2015 HTTP/1.1" 503 None

CMD responce:
F:\Download\Windows 10\ReadComicOnline Downloader (x64)>comic_dl  -i http://readcomiconline.to/Comic/Guardians-of-the-Galaxy-2015
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 9, in <module>
  File "comic_dl\comic_dl.py", line 71, in __init__
  File "comic_dl\honcho.py", line 49, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 30, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 73, in full_series
  File "comic_dl\globalFunctions.py", line 27, in page_downloader
  File "site-packages\requests\sessions.py", line 526, in get
  File "site-packages\cfscrape\__init__.py", line 47, in request
  File "site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 111, in solve_challenge
EnvironmentError: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
Failed to execute script __main__

Command sent to binary:
F:\Download\Windows 10\ReadComicOnline Downloader (x64)>comic_dl -rn 1-19 -v -i http://readcomiconline.to/Comic/Guardians-of-the-Galaxy-2015

I tried variations, all say the same error.
Perhaps this build was missing the required node.js?

OS: Windows 10 x64 (All frameworks installed, recommended phantomjs.exe file is in the directory.)
System: Intel corei5 6600k 16Gb RAM.

**Comment by Xonshiz** [comment]
Please go through the Read Me properly and check the [Dependency Installation](https://github.com/Xonshiz/comic-dl#dependencies-installation) carefully. Everything is mentioned in it.

**Comment by Tamalero** [comment]
Your dependency installation only says " It is recommended that windows users use this binary to save both, your head and time from installing all the dependencies." for the binary file
I have both files as listed.

**Comment by Xonshiz** [comment]
Did you even bother reading the read me? and the link I mentioned in my previous reply?

"This script can run on multiple Operating Systems. You need Node.js in your system's path for this script to work. Download the Node.Js from Node.js official website. Doesn't matter which operating system you're on, this is a must. Follow the instructions mentioned below, according to your OS."

"Read me"  files are written so that the user READS it before using the application of any sort. Read the VERY first paragraph of dependency installation.

**Comment by Tamalero** [comment]
I have no clue why the hell you're acting like an asshole, calm down.
I DID READ YOUR README and ITS CONFUSING.

Your own readme says the BINARY does "save you from having to install all dependencies". I'm not using the script, I'm using the WINDOWS BINARY.

Second.. your "download this" Link goes to a 404 page not found.


again, by your OWN DAMN WORDS

"**If you're on windows, then it is recommended to download the windows binary for this script. If you use the windows binary, you don't need to install anything**. But, if for some weird reason you want to use Python script instead, then follow these steps

**Comment by Xonshiz** [comment]
Holy crap, stop newbie. STOP!
Go through the read me PROPERLY and open an issue of you a Geniune problem. 

If you're new to Github, then remember, CHECK THE ALREADY OPENED/CLOSED ISSUES before you OPEN A NEW ONE! #29 is the same one that you've opened. So, you're DUMB.

**Comment by CESRO** [comment]
Since you love to silence and antagonize anyone who reports anything that is not pleasing for you.. heres my last message.

Wow, I never seen a creator with a stick so up in their ass!.

To resume:

You keep claiming "read the manual". your own manual contradicts itself!!!.

How about changing the wording to say "All versions, including Binary files, need NODE.JS"
And add that darn link in the Windows Binary section? That wasnt hard, was it?

Remember, by your own words.. right in the windows binary section it says this: "**If you're on windows, then it is recommended to download the windows binary for this script. If you use the windows binary, you don't need to install anything**" (that is a copy and paste of your manual)

A little civility goes a long way instead of being so defensive and rude. Bonus for banning my primary account.


Anyway, Good luck with whatever thing you do.

**Comment by Xonshiz** [comment]
Stop making throw away accounts. Now you know about the issue, fix it yourself.
