### ISSUE TITLE
Ransomware warning

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#75]
The latest version of the binary is triggering my MalwareBytes that it may contain 'ransomware'.  I don't honestly think that its true and its most likely a false positive.  I'm bypassing the issue by putting an exception in my MalwareBytes program.  So easy enough to work around this issue.  However, I did think you'd want to know about it.

Oh...I tested it and it happened on two different computers.  It works fine for a while, then MalwareBytes goes nuts and quarantines the binary and prompts me to reboot.

I didn't grab an error log this time since it probably isn't relevant. 

Also, I only tested this on http://readcomiconline.to.  I don't know if happens on other sites.

**Comment by Xonshiz** [comment]
Woah whaaaaat? I wanted to make a Ransomware, but not in comic-dl. Do you happen to have any other antivirus  that you can check it with?

**Comment by Xonshiz** [comment]
This is weird. All I've added is a config file. It'll write to it and read from it. PLus, I haven't included any external library in this as well. I'll need to check this on my end.

**Comment by whitewolves** [comment]
Hi,
Unlike StrangeDOS's case above, MalwareBytes does not find a problem with it on my PC. But AVAST says it's got Win32:Malware-gen.
Regards

**Comment by StrangeDOS** [comment]
Sorry.  MalwareBytes is all I'm using at present.  

Whitewolves, I've got a premium copy with ransomware scan turned on.  If you are testing with the free version of MalwareBytes, it doesn't do a ransomware scan.

**Comment by whitewolves** [comment]
Thanks StrangeDOS. 
You're correct, I am using the free version of MalwareBytes.

**Comment by Xonshiz** [comment]
What? Seriously? Even the older ones? Okay, this is something I need to investigate then. I think it might be because this application is connecting to internet, posting your credentials for batoto and retrieving the data, in 2 websites, it's retrieving encrypted data and then it decrypts it and then makes various files and sometimes changes the extensions. So, maybe THAT is triggering the ransom-ware problem.

These are the features of a ransom-ware. It's highly likely that this is the case. The antiviruses are observing a similar action or series of actions.

**Comment by StrangeDOS** [comment]
Actually this is why I submitted a bug for adding version information to the debug log...so I could accurately tell you which versions have the ransomware issue.  But the good news is that not all the older versions are doing this.  It started in the version just before the one that got the new config file switches.  No earlier than that.

**Comment by Xonshiz** [comment]
Batoto is closing down soon, yes. But, I'm not sure if they are going to keep the manga content or not. I'll leave batoto in the supported sites for now.

**Comment by StrangeDOS** [comment]
I will watch out for a new binary when you have something for me to test.

**Comment by Xonshiz** [comment]
You can pass "--version" with the comic_dl.exe file and see the version information.

**Comment by StrangeDOS** [comment]
Neat.  Its version 2018.01.10.   Thats the first version that has the issue.

**Comment by Xonshiz** [comment]
Thank you for going through all this and confirming the issue. Really, it helps a lot!

**Comment by StrangeDOS** [comment]
No problem.  Its a useful tool.  You've put in some good work on it. :)

**Comment by Xonshiz** [comment]
I don't trust and use Antiviruses (they suck). But, because a lot of users seem to trust them, I ran this comic_dl.exe on Kaspersky and it says it's safe.

You guys can check it yourself, plus I think I'll also update the readme to include how to build this on your own systems. https://virusdesk.kaspersky.com/

Antiviruses look for a signature in a file to know whether it's harmful  or not. These signature could be code statements and the instructions that program gives. Comic_dl writes, moves, reads files and also connect with internet. In some sites, it POSTS the data as well (Maybe that's why some antiviruses get triggered). In all honesty, I'm not sure why the exe started triggering antiviruses when I removed a useless code branch. One way to test would be, if any one of you guys have python installed on your system. Perhaps, you could try using the python version and see whether any antivirus acts up.

![image](https://user-images.githubusercontent.com/13240567/35134658-e3128c1c-fcfd-11e7-96dc-ed0fb232b8c2.png)

**Comment by StrangeDOS** [comment]
I'm testing the new Windows binary (Script Version : 2018.01.19) and so far so good.  I removed the exception in MalwareBytes.  So far it hasn't alerted me to a problem.  I'll have to test for a while to be sure.  And then I'll the the Python version.

**Comment by StrangeDOS** [comment]
A couple hours of running and no repeat issues.  Also, a full scan of MalwareBytes came up negative.  So I think you have a winner.

**Comment by Xonshiz** [comment]
Oh nice. Thanks a lot and if you notice any issue, please do notify me in future :)
