### ISSUE TITLE
[6844] Failed to execute script __main__

### ISSUE THREAD

**Issue by pnupy** [Xonshiz/comic-dl#83]
I have gotten this issue multiple times now and it is quite annoying. It seems to occur randomly.

Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 306, in __init__
  File "comic_dl\honcho.py", line 98, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 30, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 135, in full_series
  File "comic_dl\sites\readcomicOnlineto.py", line 42, in single_chapter
  File "comic_dl\globalFunctions.py", line 28, in page_downloader
  File "requests\sessions.py", line 521, in get
  File "site-packages\cfscrape\__init__.py", line 39, in request
  File "requests\sessions.py", line 508, in request
  File "requests\sessions.py", line 618, in send
  File "requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
[6844] Failed to execute script __main__

Here is my log (which was running in verbose mode, so it is quite long):
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1628958/Error_Log.log)

**Comment by StrangeDOS** [comment]
I think this is the same as the bug I filed #79 

The error number on the main script is different each time.  I'm not sure what it refers to.

**Comment by Xonshiz** [comment]
Hey, the error clearly states that "Connection Error". You've been hitting Readcomicsonline.to too many times and as a result your IP has been temporarily flagged. This issue has surfaced multiple times for this particular website.

There is literally nothing I can do about it this time. There's only one fix that has worked  over the time, and that is to wait for a day or two. Also, try opening the website from your browser,  clean your cache and also if you're using python script, clean the .pyc files.

Mostly, you're gonna have to wait for 1-2 days.

**Comment by StrangeDOS** [comment]
If you go to the site manually, try to open any comic for reading and then respond to the "I am not a bot" wizard", then you should be able to download again.  Just be sure that after you click on the images, you click OK.

**Comment by pnupy** [comment]
After looking up more information on error 10054 I would agree that the server is rejecting my connection, however the thing that puzzles me is that retrying the script after a few seconds seems to work fine, plus visiting the site has never asked me to verify that i'm not a bot, and I've never had to wait 1-2 days like you said. For example when I have a batch file set to run the program multiple times for different comic series, one may fail with this error, but the next will run perfectly fine. Perhaps a solution could be trying to reconnect with an exponential back off (up to a limit)?

**Comment by Xonshiz** [comment]
The issue is not that easy to pin point. It could be anything. Your connection to a particular url, your session a lot of things. Plus, I'd rather not abuse the websites by retrying and putting a limit. I'm trying to contact the readcomiconline.to folks over this to provide me with an API or something. They haven't replied yet (and I don't think that they will reply). While I want this tool to be able to get comic/manga from various websites, I also don't want to abuse those websites. Scrapping is heavy for the websites. If you're downloading a series with 100s of chapters in it, the automated script will query the website a lot of times in a short period of time. I myself run website on slow servers, so I know the pain. So, I'd just suggest that you guys also understand those issues.
