### ISSUE TITLE
"Are you human" snag

### ISSUE THREAD

**Issue by hallwayorchard** [Xonshiz/comic-dl#9]
Hi,
Love this script!

Recently I've encountered a dramatic increase in the script failing due to the human verification on readcomiconline.to.

Example attached.
[Error Log.zip](https://github.com/Xonshiz/comic-dl/files/973693/Error.Log.zip)

**Comment by Xonshiz** [comment]
Try opening the website in your browser and clear the cache. And try running the script after a few hours. I'd say after at least 9 - 10 hours.

**Comment by hallwayorchard** [comment]
This helps, but the issue repeats itself.
I think the problem occurs when I stop the script and restart a series.  If there are several issues already in place, by the time the script gets about 8 issues in it's triggering the human verification.

Is there a way to flag to start downloading at a certain issue? 

Thanks again!

**Comment by Xonshiz** [comment]
It's bringing up Human Verification because of CF. I still have to add the range functionality. I'll add it by next month. I have exams going on right now, so can't really get into this stuff right now.

**Comment by Naguz** [comment]
I had the same issue. What worked for me:
1: Delete the sites/__pycache__ folder in the comid_dl folder
2: Open a new private browsing session in your web browser and navigate to the site so yo get a "Are you human"-dialogue. I never get this if I use a browser session where I have already visited the site.
3: To start a download from a specific number, I used a bash command with seq. As an example: 
`# for i in $(seq 100 150); do ./comic_dl.py -v -i http://readcomiconline.to/Comic/Some-Comic/Issue-$i; done`
This would substitute the numbers from 100 to 150 in the link, and runs fine. If you are on windows, I'm sure you could find a similar batch script and modfiy to run comic_dl in a similar fashion. Moify the number range, and of course the link to the correct comic as needed.

**Comment by Xonshiz** [comment]
This "Human Snag" should be fixed now.

**Comment by hallwayorchard** [comment]
Just want to thank Naguz for the tip to download subsets of a run.  I'm on linux so this works perfectly.  Cheers!

And thanks again to Xonshiz... fantastic script!

**Comment by techteacher47** [comment]
Thanks for the idea, Naguz! I found the batch command that works for Windows:

FOR /L %G IN (142,1,162) DO comic_dl.exe -i http://www.omgbeaupeep.com/comics/Richie_Rich/%G

This command downloads all of the Richie Rich comics from 142-162 on the omgbeaupeep site. To modify, just change the numbers (first issue, step rate, last issue) and the link to your comic. Be sure to substitute %G for the issue number in the link.

**Comment by ShadowStriker** [comment]
First I want to thank Xonshiz for this amazing script. I would also like to thank techteacher47 for the batch command for windows.

However, I was wondering if anyone found a batch command that would work on readcomiconline with the Windows binary. 

Incorporating the batch command as above FOR /L %G IN (x,x) DO comic_dl.exe -i http://www.readcomiconline.to/Comic/NameofComic/Issue-%G creates folders with no comics and read type added to the name. I've tried different permutations, but can only get it to download when I add http://www.readcomiconline.to/Comic/NameofComic/Issue-%G?id=(4 digit number here) but since the 4 digit number is unique to each issue when it downloads the next comic the folder is named correct, but the comic is the same. I can change the 4 digit to increase by 2 (the usual change between comics) but then the folders don't work. 

I love what everyone is doing and wish as a total noob I could better help. Thanks!

**Comment by Xonshiz** [comment]
I think this range option is needed more than I thought. Hmmm, will look into it this weekend...

**Comment by Xonshiz** [comment]
@ShadowStriker @techteacher47 If anyone of you want to discuss about this "batch" workaround, please open a new issue. This issue doesn't really go with the theme :)
