### ISSUE TITLE
Error Log being created in wrong directory

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#96]
It looks like if you are using the --dd switch in conjunction with the --verbose switch, the error log is being created in whatever directory that was specified by the --dd switch instead of where the binary is.

Behavior: Error log created in my f:\DownloadComic directory.

Expected Behavior: Error log created in c:\program files\nodejs.

**Comment by Xonshiz** [comment]
Hey, this is the intended behavior. I've added this in the previous release because if the error_log is not created in the downloads directory, people often ignore it and are unable to find it. To avoid that issue, I've changed this behavior.

It's easier to find the error log where your downloaded files are, instead of the main executable's folder. Hope that makes sense. But, if you have another way of putting it, please feel free to advise me, I'll consider that option :)

**Comment by StrangeDOS** [comment]
Works for me.  It just caught me by surprise because I expected it in the nodejs directory, like before.  But you have a great point.  This does make it easier to find.  However, you might want to update the site documentation to tell people where the log is. :)

**Comment by Xonshiz** [comment]
Yep, a good point :)
